#' pop.STR frequency data
#'
#' Data was generated by selecting all possible markers and the corresponding
#' population (meta-)group in the pop.STR tool. The following datasets are
#' available:
#'
#' \describe{
#'
#' \item{ft_popstr_europe}{Europe metaregion (average of all other regions)}
#'
#' \item{ft_popstr_nw_spain}{North-West Spain (Galicia)}
#'
#' \item{ft_popstr_israel_carmel_druze}{Israel (Carmel) - Druze}
#'
#' }
#'
#' @source \url{http://spsmart.cesga.es/popstr.php}
#' @name data_popstr

#' @rdname data_popstr
"ft_popstr_europe"

#' @rdname data_popstr
"ft_popstr_nw_spain"

#' @rdname data_popstr
"ft_popstr_israel_carmel_druze"

#' US Caucasian allele frequencies
#'
#' Data extracted from the NIST 1036 Revised U.S. Population Dataset (July
#' 2017). The following collections are available:
#'
#' \describe{
#'
#' \item{ft_nist_all}{All data (average over the 1036 individuals)}
#'
#' \item{ft_nist_asian}{Asian}
#'
#' \item{ft_nist_african_american}{African American}
#'
#' \item{ft_nist_caucasian}{Caucasian}
#'
#' \item{ft_nist_hispanic}{Hispanic}
#'
#' }
#'
#' @source \url{https://strbase.nist.gov/NISTpop.htm}
#' @source Hill, C. R., Duewer, D. L., Kline, M. C., Coble, M. D., & Butler, J.
#'   M. (2013). US population data for 29 autosomal STR loci. Forensic Science
#'   International: Genetics, 7(3), e82-e83.
#' @name data_nist


#' @rdname data_nist
"ft_nist_caucasian"

#' @rdname data_nist
"ft_nist_asian"

#' @rdname data_nist
"ft_nist_african_american"

#' @rdname data_nist
"ft_nist_hispanic"

#' @rdname data_nist
"ft_nist_all"
